version: '3.8'
services:
  cirisagent_teacher:
    container_name: teacher
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - PROFILE_NAME=teacher
        - MODE_LIST=discord
    env_file:
      - .env.teacher
    volumes:
      - ./vol/teacher:/app/logs
    # command: python run_discord_teacher.py
    command: python main.py --profile teacher --modes discord